### PR TITLE
Replace Strings with Localizable Resources

### PR DESCRIPTION
**Pull request by qe201020335**
Using localizable resources allows others to properly localize the app without replacing string in a fork.

- [x] Extract and replace static strings in layout files
- [x] Extract and replace dynamic strings from code
- [x] Add an option to change language

I tried to put the new resource files in the `Assets` folder, but it didn't work, so I had to create a new folder for them. 

image

### CODE REVIEW

**Comment by qe201020335** [comment]
I will squash the small commits later

**Comment by Lauriethefish** [comment]
Heya, getting round to this now, sorry for the delay.

**Comment by Lauriethefish** [comment]
Currently attempting to find a workaround to refresh the UI without restarting the app. It seems changing theme does the trick but that's a bit *too* jank for my liking.

**Comment by Lauriethefish** [comment]
Seems there's no way to do it because `StaticResource`s have no event handler because they're, well, static.
We could make them dynamic resources but that would use more memory, so I think a restart is a good compromise for now.

**Comment by Lauriethefish** [comment]
Now lgtm, awaiting build

**Review by Lauriethefish — APPROVED** [review]

**Pull request merged**
