### PR TITLE
Backup/restore obb

### PR DESCRIPTION
**Pull request by DanTheMan827**

### CODE REVIEW

**Comment by DanTheMan827** [comment]
Oops, I forgot to leave out the bit to include the “modded” file.

**Review by RedBrumbler — APPROVED** [review]

**Comment by RedBrumbler** [comment]
I tested it out on a q2 (not sure which OS version) and it seems to work

**Comment by Lauriethefish** [comment]
LGTM although I don't see the need to force stop?

**Comment by Lauriethefish** [comment]
I see you are moving the obb, this makes sense now.

**Pull request merged**
