### PR TITLE
Quatcher, do it.

### PR DESCRIPTION
**Pull request by James-261**
Pretty sure I have changed every instance of QuestPatcher to Quatcher, gone through every file.

### CODE REVIEW

**Comment by Lauriethefish** [comment]
stop

**Comment by James-261** [comment]
never

**Comment by James-261** [comment]
next person to comment is bad

**Comment by Lauriethefish** [comment]
Due to the transganguation of the tri-linear interpole, the comment above is obviously falsified transdimentialifications, and should be removed.

Thanks.

**Comment by James-261** [comment]
ok

**Comment by James-261** [comment]
'This, however, does still not change the fact that Quatcher is superior

**Comment by Lauriethefish** [comment]
Closed since a bunch of stuff has been changed and these changes will be hard to integrate. Maybe in the future

**Pull request closed without merging**
